// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 为某个枚举单独设置错误码
func IsNeedLogin(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_NEED_LOGIN.String() && e.Code == 401
}

// 为某个枚举单独设置错误码
func ErrorNeedLogin(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_NEED_LOGIN.String(), fmt.Sprintf(format, args...))
}

func IsDbFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DB_FAILED.String() && e.Code == 500
}

func ErrorDbFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_DB_FAILED.String(), fmt.Sprintf(format, args...))
}

// 评论已经被删除
func IsReviewHasBeenDeleted(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_REVIEW_HAS_BEEN_DELETED.String() && e.Code == 401
}

// 评论已经被删除
func ErrorReviewHasBeenDeleted(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_REVIEW_HAS_BEEN_DELETED.String(), fmt.Sprintf(format, args...))
}

func IsIdErr(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ID_ERR.String() && e.Code == 401
}

func ErrorIdErr(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_ID_ERR.String(), fmt.Sprintf(format, args...))
}

func IsReviewidErr(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_REVIEWID_ERR.String() && e.Code == 401
}

func ErrorReviewidErr(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_REVIEWID_ERR.String(), fmt.Sprintf(format, args...))
}

// StoreID 和评论中的不一致
func IsStoreidReviewidMismatch(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_STOREID_REVIEWID_MISMATCH.String() && e.Code == 401
}

// StoreID 和评论中的不一致
func ErrorStoreidReviewidMismatch(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_STOREID_REVIEWID_MISMATCH.String(), fmt.Sprintf(format, args...))
}

func IsOrderReviewed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ORDER_REVIEWED.String() && e.Code == 400
}

func ErrorOrderReviewed(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_ORDER_REVIEWED.String(), fmt.Sprintf(format, args...))
}
